openapi: 3.0.0
info:
  title: Addition API
  description: The public facing API of our internal addition service
  version: 1.0.0
servers:
  - url: http://localhost:8080/
    description: The server we need you to implement
paths:
  /add:
    post:
      description: Can optionally respond synchronously with the calculated result
      requestBody:
        description: The specified calculation request
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CalculationRequest'
      parameters:
        - in: query
          name: syncResult
          schema:
            type: boolean
          description: Specifies if the result should be provided in the response
      responses:
        '200':
          description: The response for the calculation request
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/CalculationResponse'
  /list-results:
    get:
      description: Responds with a list of all results
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items:
                  allOf:
                    - $ref: '#/components/schemas/CalculationResult'
                    - type: object
                      properties:
                        asyncId:
                          type: string
                          example: 56d583ed-3e70-4e44-b5ce-d011e5a34326
                          description: The id of the requested calculation
                      required:
                        - asyncId
components:
  schemas:
    CalculationRequest:
      type: object
      properties:
        numberOne:
          type: number
          example: 4
        numberTwo:
          type: number
          example: 4.5
      required:  
        - numberOne
        - numberTwo
    CalculationResponse:
      type: object
      properties:
        asyncId:
          type: string
          example: 56d583ed-3e70-4e44-b5ce-d011e5a34326
          description: The id of the requested calculation
        syncResult:
          type: object
          example: Arthur Dent
      required:
        - asyncId
    CalculationResult:
      type: object
      properties:
        numberOne:
          type: number
          example: 4
        numberTwo:
          type: number
          example: 4.5
        result:
          type: number
          example: 8.5
      required:  
        - numberOne
        - numberTwo
        - result
